### ISSUE TITLE
Record Match Algorithm Still Produces Negtiave Elo Score

### ISSUE THREAD

**Issue by ademidun** [HankMD/EloPy#1]
This [commit](https://github.com/HankMD/EloPy/commit/ba014fa6a02bf77444cc1d9fcf480bf899e38926) #ba014fa still does not resolve the negative elo score issue. I changed the RecordMatch algorithm to use the correct elo score algorithm based on the following 2 resources. 

https://en.wikipedia.org/wiki/Elo_rating_system#Theory
https://metinmediamath.wordpress.com/2013/11/27/how-to-calculate-the-elo-rating-including-example/

@HankMD If you give me permission to make a pull-request, I can make the fix.

Original: 

    def recordMatch(self, name1, name2, winner=None, draw=False):
        """
        Should be called after a game is played.
        @param name1 - name of the first player.
        @param name2 - name of the second player.
        """
        player1 = self.getPlayer(name1)
        player2 = self.getPlayer(name2)

        expected1 = player1.compareRating(player2)
        expected2 = player2.compareRating(player1)
        
        k = len(self.__getPlayerList()) * 42

        rating1 = player1.rating
        rating2 = player2.rating

        if draw:
            score1 = 0.5
            score2 = 0.5
        elif winner == name1:
            score1 = 1.0
            score2 = 0.0
        elif winner == name2:
            score1 = 0.0
            score2 = 1.0
        else:
            raise InputError('One of the names must be the winner or draw must be True')

        newRating1 = rating1 + k * (score1 - expected1)
        newRating2 = rating2 + k * (score2 - expected2)

        if newRating1 < 0:
            newRating1 = 0
            newRating2 = rating2 - rating1

        elif newRating2 < 0:
            newRating2 = 0
            newRating1 = rating1 - rating2

        player1.rating = newRating1
        player2.rating = newRating2

Should be

    def recordMatch(self, name1, name2, winner=None, draw=False):
        """
        Should be called after a game is played.
        @param name1 - name of the first player.
        @param name2 - name of the second player.
        """
        player1 = self.getPlayer(name1)
        player2 = self.getPlayer(name2)
        k = 42 # todo pick a more sophisticated k value?

        # https://metinmediamath.wordpress.com/2013/11/27/how-to-calculate-the-elo-rating-including-example/
        rating_1_current = self.getPlayerRating(player1.name)
        rating_2_current = self.getPlayerRating(player2.name)

        rating_1_current = 10 ** (rating_1_current/400)
        rating_2_current = 10 ** (rating_2_current/400)

        expected_1 = rating_1_current / (rating_1_current + rating_2_current)
        expected_2 = rating_2_current / (rating_1_current + rating_2_current)

        if draw:
            score_1 = 0.5
            score_2 = 0.5
        elif winner == name1:
            score_1 = 1.0
            score_2 = 0.0
        elif winner == name2:
            score_1 = 0.0
            score_2 = 1.0
        else:
            raise ValueError('One of the names must be the winner or draw must be True')

        rating_1_new = rating_1_current + k * (score_1 - expected_1)
        rating_2_new = rating_2_current + k * (score_2 - expected_2)

        player1.rating = rating_1_new
        player2.rating = rating_2_new

**Comment by HankSheehan** [comment]
Hey! I added you as a collaborator. Feel free to make this PR.

**Comment by HankSheehan** [comment]
@ademidun , since I've given you the permissions I am resolving this issue. Let me know if you need anything else!
